spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      actuator:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: 'health,gatewayroutes'

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

server:
  port: 8080