spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_post_comment
  kafka:
    bootstrap-servers:
      localhost:9092
  redis:
    host: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
