spring:
  datasource:
    url: jdbc:postgresql://database:5432/blog_post_comment
  kafka:
    bootstrap-servers:
      kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8070/eureka/