spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reaction
  kafka:
    bootstrap-servers:
      localhost:9092
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/