spring:
  cache:
    type: caffeine
    caffeine:
      spec:
        maximumSize=100,expireAfterAccess=24h
  kafka:
    consumer:
      group-id: reactions-service-group-id
      auto-offset-reset: earliest
  data:
    redis:
      port: 6379
      password: ${REDIS_PASSWORD:"{cipher}720abc8f84b313cf215850ae5591f09aac4b13c93b7fddb0229895e392e30eb1"}
      database: 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:"{cipher}116c45733072ecd24f41f4ddd289261e663a42b2c7634278b2ccc3cb303370e2"}
    password: ${POSTGRES_PASSWORD:"{cipher}720abc8f84b313cf215850ae5591f09aac4b13c93b7fddb0229895e392e30eb1"}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  retry:
    instances:
      retry-reaction:
        max-attempts: 3
        wait-duration: 1s
        record-exceptions:
          - org.springframework.dao.DataAccessResourceFailureException
          - org.springframework.dao.QueryTimeoutException
          - org.springframework.dao.CannotAcquireLockException
          - org.springframework.dao.DeadlockLoserDataAccessException
  ratelimiter:
    instances:
      rate-limit-reaction:
        timeout-duration: 5s
        limit-refresh-period: 5s
        limit-for-period: 2
  circuitbreaker:
    instances:
      circuit-breaker-reaction:
        register-health-indicator: true
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - dev.mmaksymko.reactions.configs.exceptions.ExternalApiServerException

management:
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret: ${JWT_SECRET_KEY:secret}

server:
  port: 8083

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org:
      apache:
        kafka:
          clients: WARN
          common:
            utils:
              AppInfoParser: WARN