spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reaction
  kafka:
    bootstrap-servers:
      localhost:9092
  data:
    redis:
      host: localhost
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans