spring:
  datasource:
    url: jdbc:postgresql://database:5432/reaction
  kafka:
    bootstrap-servers:
      kafka:9092
  data:
    redis:
      host: redis

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8070/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans