spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  kafka:
    consumer:
      group-id: blog-post-service-group-id
      auto-offset-reset: earliest
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:"{cipher}116c45733072ecd24f41f4ddd289261e663a42b2c7634278b2ccc3cb303370e2"}
    password: ${POSTGRES_PASSWORD:"{cipher}720abc8f84b313cf215850ae5591f09aac4b13c93b7fddb0229895e392e30eb1"}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

resilience4j:
  retry:
    instances:
      retry-post:
        max-attempts: 3
        wait-duration: 1s
        record-exceptions:
          - org.springframework.dao.DataAccessResourceFailureException
          - org.springframework.dao.QueryTimeoutException
          - org.springframework.dao.CannotAcquireLockException
          - org.springframework.dao.DeadlockLoserDataAccessException
  ratelimiter:
    instances:
      rate-limit-post:
        timeout-duration: 0s
        limit-refresh-period: 5s
        limit-for-period: 2

jwt:
  secret: ${JWT_SECRET_KEY:secret}

server:
  port: 8081
