spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      actuator:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
  config:
    import: optional:configserver:http://localhost:8071

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - "*"

geolite2:
  country-location: classpath:GeoLite2-Country.mmdb
  local-hosts:
    - 127.0.0.1
    - 0:0:0:0:0:0:0:1
  blocked-counties:
    - RU
    - BY
    - IL
    - CN
    - VA

server:
  port: 8080