eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
spring:
  kafka:
    bootstrap-servers:
      localhost:9092
  data:
    redis:
      host: localhost

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans